### ISSUE TITLE
curr.sky에서 값을 리턴을 받을 수 없습니다.

### ISSUE THREAD

**Issue by ghost** [blurblah/kma#1]
저는 현재 우분투 환경에서 python 3.5.2버전으로 kma를 사용중입니다. 나머지는 다 값을 리턴을 받을 수 있었으나 하늘 정보를 못받고 있습니다. 뭐가 문제 일까요?

**Comment by blurblah** [comment]
아래와 같은 메일이 얼마전 왔었네요. 하늘상태 정보 제공은 기상청 쪽에서 종료한 것으로 보입니다.
몇달째 프로젝트 때문에 바빠서 신경 못쓰고 있는데 다음달쯤에 다시 업데이트할 생각이에요.

---

안녕하세요.

공공데이터포털 동네예보정보조회서비스를 사용하시는 사용자를 대상으로 안내메일을 보내드립니다.


동네예보정보조회서비스 초단기실황조회서비스가  관측 값 기반 정보로 변경되면서,

하늘상태, 낙뢰 요소 서비스는 제공 종료 안내(7.11)를 드린바 있습니다.

이에 하늘상태, 낙뢰 요소가 3개월간 유지 후 10.10일부로 종료되오니

아직  해당 요소를 호출 중인 사용자께서는 귀 시스템에 변경정보를  반영하여 주시기 바랍니다.

 

*  기 안내 내용 : 공공데이터 포털 공지사항(등록일 2018-07-11)

제목 :  '기상청 동네예보정보조회 OPENAPI서비스'

    - 분석 값 기반 정보에서 관측 값 기반 정보로 제공 (7.11)
     ※ 하늘상태, 낙뢰정보(분석 값 기반)는 3개월간 유지
    - 하늘상태, 낙뢰 요소는 서비스 종료 (10.10)

**Comment by blurblah** [comment]
@Speedcore300 위 내용처럼 하늘 정보를 받아올 수 없는 관계로 해당 속성을 제거하는 것으로 수정해서 pypi에도 배포해 두었습니다. version 0.3.0
